//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatsBR
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessLog
    {
        public int Id { get; set; }
        public string StatisticalNumber { get; set; }
        public string UniqueID { get; set; }
        public System.DateTime LogDate { get; set; }
        public string LogUpdateSource { get; set; }
        public string LegalName { get; set; }
        public string OperationalName { get; set; }
        public string Address { get; set; }
        public string LegalAddress { get; set; }
        public string District { get; set; }
        public string PostalCode { get; set; }
        public string PhoneNumber { get; set; }
        public string Fax { get; set; }
        public string GPS { get; set; }
        public string Email { get; set; }
        public string URL { get; set; }
        public byte BusinessTypeCode { get; set; }
        public byte BusinessStatusCode { get; set; }
        public Nullable<System.DateTime> YearBegunOperation { get; set; }
        public Nullable<System.DateTime> FiscalPeriodStart { get; set; }
        public Nullable<System.DateTime> FiscalPeriodEnd { get; set; }
        public Nullable<double> PercentForeignOwn { get; set; }
        public Nullable<double> Revenue { get; set; }
        public string RevenueSource { get; set; }
        public Nullable<System.DateTime> RevenueDate { get; set; }
        public Nullable<long> NumberOfEmployees { get; set; }
        public string NumberOfEmployeesSource { get; set; }
        public Nullable<System.DateTime> NumberOfEmployeesDate { get; set; }
        public Nullable<long> NumberOfSalariedEmployees { get; set; }
        public string NumberOfSalariedEmployeesSource { get; set; }
        public Nullable<System.DateTime> NumberOfSalariedEmployeesDate { get; set; }
        public Nullable<double> Sales { get; set; }
        public string SalesSource { get; set; }
        public Nullable<System.DateTime> SalesDate { get; set; }
        public Nullable<double> Wages { get; set; }
        public string WagesSource { get; set; }
        public Nullable<System.DateTime> WagesDate { get; set; }
        public string ISIC { get; set; }
        public string ISICSource { get; set; }
        public Nullable<System.DateTime> ISICDate { get; set; }
        public string LegalCode { get; set; }
        public string UserId { get; set; }
        public string SectorCode { get; set; }
        public Nullable<byte> ActionCode { get; set; }
    
        public virtual Business Business { get; set; }
    }
}
