//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatsBR
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExternalKey
    {
        public string StatisticalNumber { get; set; }
        public string VATNumber { get; set; }
        public string NICNumber { get; set; }
        public string IRDNumber { get; set; }
        public string RegistrarNumber { get; set; }
    
        public virtual Business Business { get; set; }
        public virtual IRD IRD { get; set; }
        public virtual NIC NIC { get; set; }
        public virtual Registrar Registrar { get; set; }
        public virtual VAT VAT { get; set; }
    }
}
