//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatsBR
{
    using System;
    using System.Collections.Generic;
    
    public partial class IRD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IRD()
        {
            this.ExternalKeys = new HashSet<ExternalKey>();
            this.IRDLogs = new HashSet<IRDLog>();
        }
    
        public string IRDNumber { get; set; }
        public string Year { get; set; }
        public string Name { get; set; }
        public string TradeName { get; set; }
        public string MailingAddress { get; set; }
        public string MailingCity { get; set; }
        public string PhoneNumber { get; set; }
        public string FaxNumber { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<int> ValTaxSupply { get; set; }
        public string Primary_ISIC { get; set; }
        public string Secondary_ISIC { get; set; }
        public Nullable<System.DateTime> TaxSuppStartDate { get; set; }
        public Nullable<byte> LegalStatus { get; set; }
        public string Representative { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExternalKey> ExternalKeys { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IRDLog> IRDLogs { get; set; }
    }
}
