//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatsBR
{
    using System;
    using System.Collections.Generic;
    
    public partial class ISICLog
    {
        public int ID { get; set; }
        public string StatisticalNumber { get; set; }
        public string ISIC { get; set; }
        public string ISICSource { get; set; }
        public Nullable<System.DateTime> ISICDate { get; set; }
        public Nullable<int> LasUserIDUpdated { get; set; }
    
        public virtual Business Business { get; set; }
    }
}
