//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatsBR
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGIN
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public string UserSurname { get; set; }
        public string LoginName { get; set; }
        public string LoginPassword { get; set; }
        public string UserEmailAddress { get; set; }
    }
}
