//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatsBR
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BusinessRegisterEntities : DbContext
    {
        public BusinessRegisterEntities()
            : base("name=BusinessRegisterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AddressLog> AddressLogs { get; set; }
        public virtual DbSet<Business> Businesses { get; set; }
        public virtual DbSet<BusinessLog> BusinessLogs { get; set; }
        public virtual DbSet<BusinessStatu> BusinessStatus { get; set; }
        public virtual DbSet<BusinessType> BusinessTypes { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<ISICLog> ISICLogs { get; set; }
        public virtual DbSet<LOGIN> LOGINs { get; set; }
        public virtual DbSet<NumEmpLog> NumEmpLogs { get; set; }
        public virtual DbSet<NumSalariedEmpLog> NumSalariedEmpLogs { get; set; }
        public virtual DbSet<OptionalBusinessAttribute> OptionalBusinessAttributes { get; set; }
        public virtual DbSet<PercentForeignLog> PercentForeignLogs { get; set; }
        public virtual DbSet<RevenueLog> RevenueLogs { get; set; }
        public virtual DbSet<SalesLog> SalesLogs { get; set; }
        public virtual DbSet<Sector> Sectors { get; set; }
        public virtual DbSet<StatisticalStructure> StatisticalStructures { get; set; }
        public virtual DbSet<WagesLog> WagesLogs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<ExternalKey> ExternalKeys { get; set; }
        public virtual DbSet<IRD> IRDs { get; set; }
        public virtual DbSet<IRDLog> IRDLogs { get; set; }
        public virtual DbSet<NIC> NICs { get; set; }
        public virtual DbSet<NICLog> NICLogs { get; set; }
        public virtual DbSet<Registrar> Registrars { get; set; }
        public virtual DbSet<RegistrarLog> RegistrarLogs { get; set; }
        public virtual DbSet<VAT> VATs { get; set; }
        public virtual DbSet<VATLog> VATLogs { get; set; }
    }
}
