//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatsBR
{
    using System;
    using System.Collections.Generic;
    
    public partial class VATLog
    {
        public string VATNumber { get; set; }
        public System.DateTime LogDate { get; set; }
        public string Year { get; set; }
        public string Month { get; set; }
        public string StandardRatedSupplies { get; set; }
        public string Hotel { get; set; }
        public string ZeroRatedSupplies { get; set; }
        public string ExemptSupplies { get; set; }
        public string TotalSupplies { get; set; }
        public string TotalOutputTax { get; set; }
    
        public virtual VAT VAT { get; set; }
    }
}
